### ISSUE TITLE
SchemaError.create_from(error) on Python3.6.9 ?

### ISSUE THREAD

**Issue by domingguss** [json-schema-org/json-schema-spec#1134]
Hi,

did something recently break when using Python 3.6.9? Because I'm running a jsonschema validation with behave in a docker image (based on ubuntu18:04) on our Gitlab Runner (amd64), but it seems like it's failing to verifying a simple json object already:

code:
```python
 json_obj = {'type': 6, 'acknowledge': 1}

context.lastJson = json_obj

schema = {}
with open('jsonscheme_type_3.json', 'r') as f:
    schema = json.loads(f.read())

jsonschema.validate(json_obj, schema)
                        
```

Strange thing is is when I run the code on my macbook, everything works, so I figured must be something in the docker image. I first thought it's because it's using python3.6.9 here, but on other machines (raspberry armv7) it works with 3.6.9...

Can someone educate me on what might goes wrong here?

logs: 
```
HOOK-ERROR in before_scenario: AssertionError: FAILED SUB-STEP: Given we are connected to the senior
Substep info: Assertion Failed: FAILED SUB-STEP: When I reset the senior
Substep info: Assertion Failed: FAILED SUB-STEP: When I reset the senior as "KURT"
Substep info: Assertion Failed: FAILED SUB-STEP: When I send json {"type": 6, "payload": {"reboot": "now", "newDeviceType": 0}}
Substep info: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 156, in send_json_with_delimiter
    jsonschema.validate(json_obj, schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 963, in validate
    cls.check_schema(schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 183, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'type': 'object', 'properties': {'address': {'type': 'number'}, 'type': {'type': 'number'}, 'state': {'anyOf': [{'type': 'number'}, {'type': 'number'}]}, 'amperage': {'type': 'number'}, 'temperature': {'type': 'number'}, 'voltage': {'type': 'number'}, 'usbVoltage': {'type': 'number'}, 'gitVersion': {'type': 'string'}, 'errors': {'type': 'number'}, 'warnings': {'type': 'number'}, 'update': {'$ref': '#/definitions/boardUpdate'}}, 'allOf': [{'if': {'properties': {'type': {'const': 1}}}, 'then': {'properties': {'sensors': {'$ref': '#/definitions/sensors'}, 'outputs': {'$ref': '#/definitions/motors'}}, 'required': ['address', 'type', 'state', 'amperage', 'temperature', 'voltage', 'usbVoltage', 'gitVersion', 'sensors']}}, {'if': {'properties': {'type': {'const': 4}}}, 'then': {'properties': {'sensors': {'$ref': '#/definitions/sensors'}, 'outputs': {'$ref': '#/definitions/outputs'}}, 'required': ['address', 'type', 'state', 'amperage', 'temperature', 'voltage', 'usbVoltage', 'errors', 'warnings']}}]}] is not of type 'object', 'boolean'
Failed validating 'type' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:
    {'$defs': {'anchorString': {'pattern': '^[A-Za-z_][-A-Za-z0-9._]*$',
                                'type': 'string'},
               'uriReferenceString': {'format': 'uri-reference',
                                      'type': 'string'},
               'uriString': {'format': 'uri', 'type': 'string'}},
     '$dynamicAnchor': 'meta',
     '$id': 'https://json-schema.org/draft/2020-12/meta/core',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     '$vocabulary': {'https://json-schema.org/draft/2020-12/vocab/core': True},
     'properties': {'$anchor': {'$ref': '#/$defs/anchorString'},
                    '$comment': {'type': 'string'},
                    '$defs': {'additionalProperties': {'$dynamicRef': '#meta'},
                              'type': 'object'},
                    '$dynamicAnchor': {'$ref': '#/$defs/anchorString'},
                    '$dynamicRef': {'$ref': '#/$defs/uriReferenceString'},
                    '$id': {'$comment': 'Non-empty fragments not allowed.',
                            '$ref': '#/$defs/uriReferenceString',
                            'pattern': '^[^#]*#?$'},
                    '$ref': {'$ref': '#/$defs/uriReferenceString'},
                    '$schema': {'$ref': '#/$defs/uriString'},
                    '$vocabulary': {'additionalProperties': {'type': 'boolean'},
                                    'propertyNames': {'$ref': '#/$defs/uriString'},
                                    'type': 'object'}},
     'title': 'Core vocabulary meta-schema',
     'type': ['object', 'boolean']}
On schema['properties']['payload']['properties']['boards']['items']:
    [{'allOf': [{'if': {'properties': {'type': {'const': 1}}},
                 'then': {'properties': {'outputs': {'$ref': '#/definitions/motors'},
                                         'sensors': {'$ref': '#/definitions/sensors'}},
                          'required': ['address',
                                       'type',
                                       'state',
                                       'amperage',
                                       'temperature',
                                       'voltage',
                                       'usbVoltage',
                                       'gitVersion',
                                       'sensors']}},
                {'if': {'properties': {'type': {'const': 4}}},
                 'then': {'properties': {'outputs': {'$ref': '#/definitions/outputs'},
                                         'sensors': {'$ref': '#/definitions/sensors'}},
                          'required': ['address',
                                       'type',
                                       'state',
                                       'amperage',
                                       'temperature',
                                       'voltage',
                                       'usbVoltage',
                                       'errors',
                                       'warnings']}}],
      'properties': {'address': {'type': 'number'},
                     'amperage': {'type': 'number'},
                     'errors': {'type': 'number'},
                     'gitVersion': {'type': 'string'},
                     'state': {'anyOf': [{'type': 'number'},
                                         {'type': 'number'}]},
                     'temperature': {'type': 'number'},
                     'type': {'type': 'number'},
                     'update': {'$ref': '#/definitions/boardUpdate'},
                     'usbVoltage': {'type': 'number'},
                     'voltage': {'type': 'number'},
                     'warnings': {'type': 'number'}},
      'type': 'object'}]
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 156, in send_json_with_delimiter
    jsonschema.validate(json_obj, schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 963, in validate
    cls.check_schema(schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 183, in check_schema
    raise exceptions.SchemaError.create_from(error)
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 84, in step_impl
    """.format(string))
  File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
    assert False, message
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 27, in step_impl
    """)
  File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
    assert False, message
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 18, in step_impl
    """)
  File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
    assert False, message
  Background: configure motor, input and output board  # inputBoard/wait_for_sensor.feature:3
Rebooting senior, finishing Scenario
Tx -->:  {"type": 6, "payload": {"reboot": "now"}}@#@
to validate with jsonscheme: >>>{'type': 6, 'acknowledge': 1}<<<
HOOK-ERROR in after_scenario: AssertionError: FAILED SUB-STEP: When I reboot the senior without waiting
Substep info: Assertion Failed: FAILED SUB-STEP: When I send json {"type": 6, "payload": {"reboot": "now"}}
Substep info: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 156, in send_json_with_delimiter
    jsonschema.validate(json_obj, schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 963, in validate
    cls.check_schema(schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 183, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'type': 'object', 'properties': {'address': {'type': 'number'}, 'type': {'type': 'number'}, 'state': {'anyOf': [{'type': 'number'}, {'type': 'number'}]}, 'amperage': {'type': 'number'}, 'temperature': {'type': 'number'}, 'voltage': {'type': 'number'}, 'usbVoltage': {'type': 'number'}, 'gitVersion': {'type': 'string'}, 'errors': {'type': 'number'}, 'warnings': {'type': 'number'}, 'update': {'$ref': '#/definitions/boardUpdate'}}, 'allOf': [{'if': {'properties': {'type': {'const': 1}}}, 'then': {'properties': {'sensors': {'$ref': '#/definitions/sensors'}, 'outputs': {'$ref': '#/definitions/motors'}}, 'required': ['address', 'type', 'state', 'amperage', 'temperature', 'voltage', 'usbVoltage', 'gitVersion', 'sensors']}}, {'if': {'properties': {'type': {'const': 4}}}, 'then': {'properties': {'sensors': {'$ref': '#/definitions/sensors'}, 'outputs': {'$ref': '#/definitions/outputs'}}, 'required': ['address', 'type', 'state', 'amperage', 'temperature', 'voltage', 'usbVoltage', 'errors', 'warnings']}}]}] is not of type 'object', 'boolean'
Failed validating 'type' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:
    {'$defs': {'anchorString': {'pattern': '^[A-Za-z_][-A-Za-z0-9._]*$',
                                'type': 'string'},
               'uriReferenceString': {'format': 'uri-reference',
                                      'type': 'string'},
               'uriString': {'format': 'uri', 'type': 'string'}},
     '$dynamicAnchor': 'meta',
     '$id': 'https://json-schema.org/draft/2020-12/meta/core',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     '$vocabulary': {'https://json-schema.org/draft/2020-12/vocab/core': True},
     'properties': {'$anchor': {'$ref': '#/$defs/anchorString'},
                    '$comment': {'type': 'string'},
                    '$defs': {'additionalProperties': {'$dynamicRef': '#meta'},
                              'type': 'object'},
                    '$dynamicAnchor': {'$ref': '#/$defs/anchorString'},
                    '$dynamicRef': {'$ref': '#/$defs/uriReferenceString'},
                    '$id': {'$comment': 'Non-empty fragments not allowed.',
                            '$ref': '#/$defs/uriReferenceString',
                            'pattern': '^[^#]*#?$'},
                    '$ref': {'$ref': '#/$defs/uriReferenceString'},
                    '$schema': {'$ref': '#/$defs/uriString'},
                    '$vocabulary': {'additionalProperties': {'type': 'boolean'},
                                    'propertyNames': {'$ref': '#/$defs/uriString'},
                                    'type': 'object'}},
     'title': 'Core vocabulary meta-schema',
     'type': ['object', 'boolean']}
On schema['properties']['payload']['properties']['boards']['items']:
    [{'allOf': [{'if': {'properties': {'type': {'const': 1}}},
                 'then': {'properties': {'outputs': {'$ref': '#/definitions/motors'},
                                         'sensors': {'$ref': '#/definitions/sensors'}},
                          'required': ['address',
                                       'type',
                                       'state',
                                       'amperage',
                                       'temperature',
                                       'voltage',
                                       'usbVoltage',
                                       'gitVersion',
                                       'sensors']}},
                {'if': {'properties': {'type': {'const': 4}}},
                 'then': {'properties': {'outputs': {'$ref': '#/definitions/outputs'},
                                         'sensors': {'$ref': '#/definitions/sensors'}},
                          'required': ['address',
                                       'type',
                                       'state',
                                       'amperage',
                                       'temperature',
                                       'voltage',
                                       'usbVoltage',
                                       'errors',
                                       'warnings']}}],
      'properties': {'address': {'type': 'number'},
                     'amperage': {'type': 'number'},
                     'errors': {'type': 'number'},
                     'gitVersion': {'type': 'string'},
                     'state': {'anyOf': [{'type': 'number'},
                                         {'type': 'number'}]},
                     'temperature': {'type': 'number'},
                     'type': {'type': 'number'},
                     'update': {'$ref': '#/definitions/boardUpdate'},
                     'usbVoltage': {'type': 'number'},
                     'voltage': {'type': 'number'},
                     'warnings': {'type': 'number'}},
      'type': 'object'}]
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 156, in send_json_with_delimiter
    jsonschema.validate(json_obj, schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 963, in validate
    cls.check_schema(schema)
  File "/usr/local/lib/python3.6/dist-packages/jsonschema/validators.py", line 183, in check_schema
    raise exceptions.SchemaError.create_from(error)
Traceback (of failed substep):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/builds/scentronix/hardware/stm32/kurt2/features/steps/senior_communication/communication.py", line 59, in step_impl
    """.format(string))
  File "/usr/local/lib/python3.6/dist-packages/behave/runner.py", line 404, in execute_steps
    assert False, message
```

**Comment by Relequestual** [comment]
It looks like you're using https://github.com/Julian/jsonschema
